### ISSUE TITLE
Output lists, not joined strings

### ISSUE THREAD

**Issue by atz** [sul-dlss/terraform-module-aws-network#7]
These lines:
https://github.com/sul-dlss/terraform-module-aws-network/blob/master/data/output.tf#L5-L19

do:
```hcl
output "public_subnets" {
  value = "${join(",", local.public_subnets)}"
}

output "private_subnets" {
  value = "${join(",", local.private_subnets)}"
}

output "database_subnets" {
  value = "${join(",", local.database_subnets)}"
}

output "elasticache_subnets" {
  value = "${join(",", local.elasticache_subnets)}"
}
```

Seems like this introduces ugly downstream workarounds where the joined strings are being resplit (and sometimes having to call `element` on the result).  

If `data` just provided a list output, then consumers would not need to resplit and could call `private_subnets.0` instead of `element`.  The correct signature of this component is that it is returning multiple (plural) values, so a list return makes sense.  

See: https://www.terraform.io/docs/configuration/outputs.html#example

**Comment by jonrober** [comment]
This is a workaround due to Terraform not returning lists properly from a module.  Once 0.12 is out, they've said it will work correctly, and  we can clean up a lot of this annoying code.

**Comment by atz** [comment]
I think you misunderstand the dimensions of that bug.  It does not seem to affect what I propose.  (I already used "lists in"/"lists out" in the recent sinopia code.)  I wrote up an [isolated example](https://gist.github.com/atz/9e2e60e3454921f3594d6dbc681bb4ba), and I can't see anything that breaks.

The only thing that we can't yet do is leave out the brackets, but that is unimportant to fixing the signatures of our modules.

**Comment by jonrober** [comment]
Oh, excellent then.  I hadn't looked into the bug directly myself -- Erin mentioned it as a reason that she did things that way, that both from experience and bug reports that returning lists weren't working, and that there was a future fix on the roadmap but not yet there.  That was a while ago, so I'd checked again off of yours to see if it looked like it was fixed.  I'd found a pending bugfix that sounded an awful lot like what Erin had mentioned, but yeah, it sounds like that one was a red herring and we can proceed with this.  Cool because yeah, seriously the existing code is an ugly thing.

**Comment by atz** [comment]
@jonrober put in PR #10 for it.

**Comment by jonrober** [comment]
Approved.
